### ISSUE TITLE
Lean does not recognize `user_command` attribute.

### ISSUE THREAD

**Issue by andrejbauer** [formalabstracts/formalabstracts#18]
I am on Lean 3.2.0 from Homebrew on a Mac:

    $ lean --version
    Lean (version 3.2.0, Release)

Unfortunately I get

    $ lean --githash
    GITDIR-NOTFOUND

presumably because this is a Homebrew Lean. Anyhow, what version is needed for the `@[user_command]` thingy in `meta_data.lean` to work?

**Comment by robertylewis** [comment]
Uh oh, it looks like user commands were added a day after the 3.2 release. I knew they were added at about the same time as coinductive predicates, which are in 3.2, but the couple day's delay makes all the difference.

Just to confirm, the examples here don't work for you, right? https://github.com/leanprover/lean/blob/89136339ff8c551a2313b22e92d38c1d76d33606/tests/lean/run/coinductive.lean

**Comment by andrejbauer** [comment]
They seem to work, except for the `example` thing at the bottom of the file.

**Comment by robertylewis** [comment]
Unfortunately, it's pretty hard to do any real development on release versions of Lean right now. We might want to (temporarily) base this project on the Git version of Lean. There are two things that will be added soon that will be useful for us (a tactic version of the `#print axioms` command, and user-defined attributes with parameters), and we'd have to wait at least a couple months for the next release.

**Comment by robertylewis** [comment]
Once our user base grows beyond "people who were at Big Proof" we should be more careful about versioning, of course. But this does raise a question: who is responsible for updating abstracts if/when they break with new Lean releases? We've been discussing how to handle external libraries in the Lean project quite a bit. But it's not clear to me that this project would count as an "official" repository that the Lean developers are responsible for maintaining. So do authors need to keep their own fabstracts updated? (Everything will be dead in six months.) Or do the "curators" keep things updated? (This doesn't scale well.)

**Comment by andrejbauer** [comment]
So you want me to compile Lean, eh?

We're not the only ones in the world trying to avoid versioning hell. OCaml people seem to have a very good system with the OPAM package manager, and of course there is Debian, CTAN, CPAN, etc.

It seems to me that perhaps we should develop a truly distributed system in which there is more than one fabstract repository, and then each of them is tied to some version of Lean. That is, we should develop a Lean package called `fabstracts` and let people create their one formal abstracts repositories. The only thing needed after that is a central directory where people can register their fabstract repositories (maybe this happens automagically using our package). The central repository would have to be version-aware.

**Comment by robertylewis** [comment]
That sounds nice, but it also feels like planning a highway network while everyone is still riding bicycles. We're experimenting right now to figure out what the stumbling blocks are going to be, right? Well, we've identified versioning as a stumbling block. Whatever solution we come to is going to depend somewhat on how versioning is handled in other Lean repos, and that's still not settled. While we're still experimenting, I think it's reasonable to postpone the decision and assume everyone is working with the latest Git version. It really shouldn't be too hard to compile. :)

**Comment by andrejbauer** [comment]
I compiled Lean (and before that had to update Xcode and Homebrew, and took kids to lunch).
