### ISSUE TITLE
Author identification?

### ISSUE THREAD

**Issue by favonia** [formalabstracts/formalabstracts#29]
I wish that authors can be identified by not just their names but also (optionally) their ORCID, ResearcherID, DAI, etc. This would require changes to the metadata format in `meta_data.lean`.

**Comment by andrejbauer** [comment]
Yeah, this is of course a good idea. The only thing to worry about is that we might end up making things so complicated nobody will know how to use the system. Perhaps we can have a `person` datatype, similar to `result` in `cite` in `meta_data.lean`.

**Comment by fpvandoorn** [comment]
I like this idea. We could make a `Person` datatype with multiple fields (all except name are optional), and a coercion from `string` to `Person`.

**Comment by robertylewis** [comment]
Semi-relatedly, I had the half-formed idea yesterday that we could use hole commands (https://github.com/leanprover/lean/blob/cfa34dc83e0f2ef3c1e45cbe9078e472b041cf07/library/init/meta/hole_command.lean) to automatically pull paper metadata from MathSciNet and populate our `meta_data` objects. This would make it less inconvenient to have complicated `meta_data` objects, since constructing them by hand would be less common.

**Comment by andrejbauer** [comment]
Magic confuses normal people, let's not have coercions from strings to people. Also, if a person is identified as `ORCID "7129879234"` that's rather annoying. Is there a way to write

    Person "Andrej Bauer"

in the simple case and something like

    Person "Andrej Bauer" [institution := "University of Ljubljana", orcid := "007"]

in the fancy case?

**Comment by digama0** [comment]
I would suggest `{name := "Andrej Bauer"}` and `{name := "Andrej Bauer", institution := "University of Ljubljana", orcid := "007"}`; we can use optional arguments to support this.

**Comment by favonia** [comment]
Personally I am fine with all the proposed syntax above, but I am not sure how useful `institution` is in terms of identifying people who are still alive. Maybe an email address speaks more.

**Comment by spitters** [comment]
Here's a related emacs plugin:
https://github.com/cute-jumper/gscholar-bibtex
