### ISSUE TITLE
Timestamps for URLs?

### ISSUE THREAD

**Issue by favonia** [formalabstracts/formalabstracts#30]
As you all know, a URL is hardly a reliable pointer but sometimes necessary. I wonder if we should at least timestamp every URL by the visit/retrieval date.

**Comment by andrejbauer** [comment]
What good will that do? If the URL is broken it's broken, and it's not at all helpful to know that some time in the past it was not broken.

**Comment by favonia** [comment]
If the web page was archived by Wayback, Archive-It, or any other similar service, then it is still possible to retrieve the content even when original website is down, and the visit date would help identify the correct version.

**Comment by andrejbauer** [comment]
And nobody will bother doing that, and there is an *if* in "if the web page was archived"...

**Comment by favonia** [comment]
@andrejbauer You might want to know that your personal website has been crawled at least hundreds of times by these services. For example I can find [a snapshot of your announcement of Eff 3.0 back in 2012](https://web.archive.org/web/20120430163434/http://math.andrej.com/2012/03/08/eff-3-0/). Therefore I think the *if* is actually *very possible*. I will leave the question of "whether other people know and will use these tools" to others; I do, but I cannot speak for others.

**Comment by andrejbauer** [comment]
Let me put it this way: I am too lazy to bother with timestamps. I think that's an honest answer at least ;-)

**Comment by digama0** [comment]
I am pretty sure web page archival is a non-goal of this project. We've all been using the web long enough to know the limitations of URLs, and DOIs were invented to solve this problem. Suffice it to say, this is not the best method to refer to a resource, but it is a way, and it's better than nothing. I think no action is necessary.

**Comment by andrejbauer** [comment]
One strategy is not to invent problems in order to solve them, but rather to wait for them to actually appear. This goes against the instincts of a typical mathematician, who spends their life inventing problems.

**Comment by favonia** [comment]
@andrejbauer Alright. I think I understood the pros and cons and so I am fine with either.
@digama0 Sorry I am confused by your comment. I did not propose archiving anything by ourselves, but only keeping an optional, additional piece of information to help locate it, if it exists. I am not against using URLs either.

**Comment by digama0** [comment]
I mean to say that we should not spend any additional effort to ensure that URLs are current, although of course we can review and update/remove any dead links that are discovered, on demand. Besides, you can use the commit history to extract the date at which a URL is added, so having dates in the file seems redundant.

**Comment by favonia** [comment]
I would like to clarify that the goal of this proposal is not to keep URLs current. On the contrary, the goal is to make it safe to leave possibly outdated URLs in the repository forever, and that no one can really complain even if they find an outdated URL. (They can help update the URLs, of course.)

I would also like to point out that git commit histories are very fragile and difficult to use. For example, if you rename a file, it is not so trivial to trace the information back to the original commit. Even with a perfect git, philosophically (as a design principle) and practically (from my experience), I am still against using the commit history to maintain any information we really want to preserve. The snapshot of the current repository should contain all the information we definitely care about. One practical consideration is that many academic data archiving services run with the logic of "the current snapshot is enough" and the commit history can be easily lost.

**Comment by favonia** [comment]
Hi all, even though (it seems) I disagree with the reasons given by @digama0, the conclusion was already made, and so I plan to close this issue in 24 hours due to lack of interest.

**Comment by andrejbauer** [comment]
Since there is a "reopen" button we can close now and reopen if something comes up. One has to generally always fight accumulating stale issues. They seem to exist in every project.
