### ISSUE TITLE
Support for continuous integration (TravisCI)

### ISSUE THREAD

**Issue by picrin** [formalabstracts/formalabstracts#36]
Adding support for continuous intergration using TravisCI

**Comment by picrin** [comment]
Travis doesn't [support lean at the momemnt](https://docs.travis-ci.com/user/languages/), but this can be perhaps worked around by downloading lean with another, supported, language (say python), and then executing this executable with python.

**Comment by digama0** [comment]
The "null language" in Travis is `bash`. Just use that to download and install lean. See also the https://github.com/leanprover/lean repository, which uses Travis CI for continuous integration (as well as AppVeyor).

**Comment by favonia** [comment]
@picrin The "support" is just an image populated with expected tools for that language, and you can start from any image (probably a simple one) and install the tools by yourself. Usually I start with the one configured for C, but maybe there is a better choice.

@digama0 Yes, but the structure used by the Lean main repo would be over-killing for this project.

Also I suggest using Docker (for public images) or Travis cache or whatever to reduce build time.

**Comment by favonia** [comment]
(PS: I did not submit a PR because setting these up properly requires admin permission.)

**Comment by picrin** [comment]
I've written a fugly python script #39. Both @digama0 and @favonia should have invites to collaborator status. Please comment on the PR directly

**Comment by robertylewis** [comment]
Closed by #45
