### ISSUE TITLE
Should we use unreleased, experimental features of Lean?

### ISSUE THREAD

**Issue by favonia** [formalabstracts/formalabstracts#40]
I open this issue not because I am against the current situation but because I want to isolate this issue from the discussions in #37, #38 and #39.

Let me start by defending the current situation a little bit with my 1.618 cents, in response to the worries brought up by @picrin.

1. Deployment of some special versions of Lean can be solved by providing binary builds, images or whatever somewhere, if our user base grows so quickly before the Lean team releases the next version.

2. I believe the difference in the CI script (due to compiling Lean by ourselves) is at most 10 lines of code (7-8 lines from https://github.com/leanprover/lean/blob/master/doc/make/ubuntu-16.04.md plus 2-3 other lines for caching) and thus we should not worry about it.

**Comment by picrin** [comment]
I find both reasons convincing. I'll try to get the CI working in the spirit of what @favonia is suggesting.

**Comment by Kha** [comment]
I've asked @leodemoura about providing official nightly releases of Lean. We could use these not just for this project but also first-party Lean packages like `library_dev`.

**Comment by andrejbauer** [comment]
I agree with everything. Let me also say that as soon as possible, we should get things fixed so that we rely on an official Lean release (presumably 3.3.0), rather than the development version. But until then, let's not regress to 3.2.0 as that would destroy the super cool `unfinished` feature.

**Comment by robertylewis** [comment]
Lean is changing very fast right now, and 3.2 was just released recently. We're already making use of one new feature, and presumably there will be many more we'll want to use before 3.3. Considering how small this project is, I agree that it makes much more sense to use development versions of Lean. Planning to stabilize at 3.3 seems like a good goal.

**Comment by favonia** [comment]
Let me close this now because it seems there's nothing left to do or discuss. We all agree that we can and should use the stable version as soon as Lean 3.3 (or something like that) is out. Please feel free to reopen this issue if you feel otherwise.
