### ISSUE TITLE
how to express the "intersection of all sigma algebras"?

### ISSUE THREAD

**Issue by thalesant** [formalabstracts/formalabstracts#54]
A sigma algebra is defined as a class in measure_theory.lean:

```
variables {X : Type} (σ : set (set X))

class sigma_algebra :=
(univ_mem : univ ∈ σ)
(closed_under_comp : ∀ s, s ∈ σ → univ \ s ∈ σ)
(closed_under_countable_union : ∀ f : ℕ → set X, (∀ n, f n ∈ σ) → countable_union f ∈ σ)
```

I want to say that the sigma-algebra of all Borel sets in R^n (vector R n) is the intersection of all sigma-algebras that contain the opens sets in R^n.  I'm  not sure how to take hold of all sigma algebras on a given type.   Is it obvious how to do this without essentially re-implementing the def of sigma-algebra?

**Comment by digama0** [comment]
I haven't used the repo in a while so this might not typecheck, but the most literal translation of what you just said is

    def algebra_closure (A : set (set X)) :=
    ⋂₀ {σ : set (set X) | sigma_algebra σ ∧ A ⊆ σ}

The `sigma_algebra` is only a conjunction of `Prop`s so it can safely be defined in `Prop`, but if you want to keep it in `Type`, just write `nonempty (sigma_algebra σ)` instead.

**Comment by thalesant** [comment]
`nonempty(sigma_algebra σ)` works. Thanks!
