### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by picrin** [formalabstracts/formalabstracts#9]
Running `lean --make` from the top of the repository raises multiple errors in Bauer_A_InjBaireNat.

I belive that imports of metadata structure should be prefixed with triple dot.

`/home/picrin/programming/formalabstracts/fabstract/Wiles_A_and_Taylor_R_FermatLast/fabstract.lean:1:0: error: file 'meta_data' not found in the LEAN_PATH
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:1:0: error: file 'meta_data' not found in the LEAN_PATH
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:1:0: error: file 'folklore/categories' not found in the LEAN_PATH
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:1:0: error: file 'folklore/toposes' not found in the LEAN_PATH
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/realizability.lean:1:0: error: file 'folklore/toposes' not found in the LEAN_PATH
/home/picrin/programming/formalabstracts/fabstract/Wiles_A_and_Taylor_R_FermatLast/fabstract.lean:1:0: error: invalid import: meta_data
could not resolve import: meta_data
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/realizability.lean:5:0: error: invalid import: folklore.toposes
could not resolve import: folklore.toposes
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/realizability.lean:11:17: error: unknown identifier 'topos'
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:4:0: warning: imported file '/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/realizability.lean' uses sorry
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:4:0: error: invalid import: meta_data
could not resolve import: meta_data
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:4:0: error: invalid import: folklore.categories
could not resolve import: folklore.categories
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:4:0: error: invalid import: folklore.toposes
could not resolve import: folklore.toposes
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:4:0: error: invalid import: folklore.toposes
could not resolve import: folklore.toposes
/home/picrin/programming/formalabstracts/fabstract/Wiles_A_and_Taylor_R_FermatLast/fabstract.lean:9:23: error: unknown identifier 'meta_data'
/home/picrin/programming/formalabstracts/fabstract/Wiles_A_and_Taylor_R_FermatLast/fabstract.lean:9:36: error: invalid structure value {...}, expected type is known, but it is not a structure
  ⁇
[sorry]
no axioms
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:15:0: warning: declaration 'Bauer_A_InjBaireNat.T' uses sorry
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:17:17: error: invalid field notation, type is not of the form (C ...) where C is a constant
  T
has type
  ⁇
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:17:21: error: invalid field notation, type is not of the form (C ...) where C is a constant
  ⁇
has type
  ?m_1
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:17:11: error: don't know how to synthesize placeholder
context:
⊢ Sort ?
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:18:22: error: invalid field notation, type is not of the form (C ...) where C is a constant
  T
has type
  ⁇
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:18:36: error: invalid field notation, type is not of the form (C ...) where C is a constant
  ⁇
has type
  ?m_1
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:18:11: error: don't know how to synthesize placeholder
context:
⊢ Sort ?
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:20:23: error: invalid field notation, type is not of the form (C ...) where C is a constant
  T
has type
  ⁇
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:20:43: error: invalid field notation, type is not of the form (C ...) where C is a constant
  ⁇
has type
  ?m_1
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:22:27: error: unknown identifier 'monomorphism'
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:22:27: error: function expected at
  ⁇
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:24:5: error: invalid namespace name 'result'
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:26:16: error: unknown identifier 'meta_data'
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:30:14: error: unknown identifier 'Construction'
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:31:14: error: unknown identifier 'Construction'
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:32:14: error: unknown identifier 'Proof'
/home/picrin/programming/formalabstracts/fabstract/Bauer_A_InjBaireNat/fabstract.lean:26:29: error: invalid structure value {...}, expected type is known, but it is not a structure
  ⁇
`

**Comment by fpvandoorn** [comment]
We have a choice:
- either we force every user to run `leanpkg configure` (or `~/path/to/lean/bin/leanpkg configure`) in the main directory of this repository
- or we only import files with relative paths (i.e. use triple dots)

For more info, see [here](https://github.com/leanprover/lean/tree/master/leanpkg). 

I like option 1 better.

**Comment by andrejbauer** [comment]
It's not too much to ask for `leanpkg configure`.

**Comment by andrejbauer** [comment]
In #12 we add instructions on running `leanpkg configure`, I think it's fair to close this issue once that gets pulled. I agree that we should strive for relative imports, but we should also ask the user to configure the repo, as it's not such a big deal.
